const fs = require('fs');
let d = fs.readFileSync('src/pages/Customer/Dashboard.jsx', 'utf8');
const r = '\uFFFD';
d = d.replace(new RegExp('G' + r + 'ncel Turlar' + r + 'm', 'g'), 'Güncel Turlarým');
d = d.replace(new RegExp(r + 'u an kay' + r + 'tl' + r + ' oldu' + r + 'unuz', 'g'), 'Þu an kayýtlý olduðunuz');
d = d.replace(new RegExp('U' + r + 'u' + r + ' & Transfer', 'g'), 'Uçuþ & Transfer');
d = d.replace(new RegExp('Tur Program' + r + 'span>', 'g'), 'Tur Programý</span>');
d = d.replace(new RegExp('color: \\'var\\(--primary\\)\\'}' + r + 'ehir Rehberi', 'g'), 'color: \\'var(--primary)\\'}}>Þehir Rehberi');
d = d.replace(new RegExp('Ge' + r + 'mi' + r + ' Turlar' + r + 'm', 'g'), 'Geçmiþ Turlarým');
d = d.replace(new RegExp('Hen' + r + 'z ge' + r + 'mi' + r + ' bir seyahatiniz', 'g'), 'Henüz geçmiþ bir seyahatiniz');
d = d.replace(new RegExp('Detayl' + r + ' De' + r + 'erlendirme', 'g'), 'Detaylý Deðerlendirme');
d = d.replace(new RegExp('y' + r + 'ld' + r + 'z', 'g'), 'yýldýz');
d = d.replace(new RegExp('de' + r + 'erlendirdiniz', 'g'), 'deðerlendirdiniz');
d = d.replace(new RegExp('i' + r + 'in detaylar' + r + ' puanlay' + r + 'n', 'g'), 'için detaylarý puanlayýn');
d = d.replace(new RegExp('hakk' + r + 'nda d' + r + r + r + 'ncelerinizi payla' + r + r + 'n', 'g'), 'hakkýnda düþüncelerinizi paylaþýn');
d = d.replace(new RegExp('>' + r + 'ptal<', 'g'), '>Ýptal<');
d = d.replace(new RegExp('>G' + r + 'nder<', 'g'), '>Gönder<');
d = d.replace(new RegExp('Puanlad' + r + 'n' + r + 'z', 'g'), 'Puanladýnýz');
d = d.replace(new RegExp('g' + r + 'nderdi' + r + 'iniz i' + r + 'in te' + r + 'ekk' + r + 'r', 'g'), 'gönderdiðiniz için teþekkür');
d = d.replace(new RegExp('B' + r + 'lge Seyahat Uzman' + r + 'n' + r + 'z', 'g'), 'Bölge Seyahat Uzmanýnýz');
d = d.replace(new RegExp('Turlar' + r + 'm', 'g'), 'Turlarým');
d = d.replace(new RegExp('Tur Program' + r + '</span>', 'g'), 'Tur Programý</span>');
d = d.replace(new RegExp('}>' + r + 'ehir Rehberi', 'g'), '}>Þehir Rehberi');
fs.writeFileSync('src/pages/Customer/Dashboard.jsx', d, 'utf8');
console.log('Fixed correctly');
