const fs = require('fs');
const path = 'C:/Users/otina/.gemini/antigravity/scratch/travel-app/src/pages/Customer/DestinationGuide.jsx';
let content = fs.readFileSync(path, 'utf8');

const weatherFixRegex = /if \(geoData\.results && geoData\.results\.length > 0\) \{[\s\S]*?\} \/\//;

const fixWeather = `if (geoData.results && geoData.results.length > 0) {
                    const { latitude, longitude } = geoData.results[0];
                    // 2. Forecast
                    const weatherRes = await fetch(\`https://api.open-meteo.com/v1/forecast?latitude=\${latitude}&longitude=\${longitude}&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=auto\`);
                    const weatherData = await weatherRes.json();
                    
                    if (weatherData.daily) {
                        const todayTemp = Math.round(weatherData.daily.temperature_2m_max[0]);
                        // Mapped simplified weather conditions from WMO code
                        const code = weatherData.daily.weather_code[0];
                        let condition = 'Açık';
                        if (code >= 1 && code <= 3) condition = 'Parçalı Bulutlu';
                        if (code >= 45 && code <= 48) condition = 'Sisli';
                        if (code >= 51 && code <= 67) condition = 'Yağmurlu';
                        if (code >= 71 && code <= 82) condition = 'Karlı';
                        if (code >= 95) condition = 'Fırtınalı';

                        setWeather({
                            temp: \`\${todayTemp}°C\`,
                            condition,
                            forecast: weatherData.daily.temperature_2m_max.map((t, i) => ({
                                date: new Date(weatherData.daily.time[i]).toLocaleDateString('tr-TR', {weekday: 'short'}),
                                max: Math.round(t),
                                min: Math.round(weatherData.daily.temperature_2m_min[i])
                            })).slice(0, 5) // Show next 5 days
                        });
                    }
                } else {
                    setWeather({ temp: '-', condition: 'Bulunamadı', forecast: [] });
                }
                //`;

content = content.replace(weatherFixRegex, fixWeather);

const fixRest = `// 2. Restaurants
                service.textSearch({ query: \`best rated restaurants in \${city}\` }, (restResults, restStatus) => {
                    if (restStatus === window.google.maps.places.PlacesServiceStatus.OK && restResults) {
                        setRestaurants(restResults.slice(0, 4).map(r => {
                            let cuisine = 'Restoran';
                            if (r.types) {
                                const validTypes = r.types.filter(t => !['establishment', 'point_of_interest', 'food', 'restaurant', 'store'].includes(t));
                                if (validTypes.length > 0) {
                                    cuisine = validTypes[0].replace(/_/g, ' ');
                                }
                            }
                            return {
                                name: r.name,
                                cuisine: cuisine,
                                rating: r.rating || 'Yeni'
                            };
                        }));
                    } else {`;

// Replace restaurant block
content = content.replace(/\/\/ 2\. Restaurants[\s\S]*?\} else \{/, fixRest);

// Fix unicode encoding errors generated by powershell inside the original file injection
content = content.replace(/Ak/g, 'Açık');
content = content.replace(/Paral Bulutlu/g, 'Parçalı Bulutlu');
content = content.replace(/YaYmurlu/g, 'Yağmurlu');
content = content.replace(/Karl/g, 'Karlı');
content = content.replace(/Frtnal/g, 'Fırtınalı');
content = content.replace(/Hatas/g, 'Hatası');
content = content.replace(/Alnamad/g, 'Alınamadı');
content = content.replace(/eYer/g, 'eğer');
content = content.replace(/girilmemiYse/g, 'girilmemişse');
content = content.replace(/LǬtfen/g, 'Lütfen');
content = content.replace(/eklenmiY/g, 'eklenmiş');
content = content.replace(/YǬklenemedi/g, 'Yüklenemedi');
content = content.replace(/Geersiz/g, 'Geçersiz');
content = content.replace(/Anahtar/g, 'Anahtarı');
content = content.replace(/BaYlant/g, 'Bağlantı');
content = content.replace(/Sonu/g, 'Sonuç');
content = content.replace(/Bulunamad/g, 'Bulunamadı');
content = content.replace(/zin/g, 'İzin');
content = content.replace(/\?ehir/g, 'Şehir');
content = content.replace(/PopǬler/g, 'Popüler');

fs.writeFileSync(path, content, 'utf8');
console.log('Successfully patched DestinationGuide properties!');
